USE QLNH
GO

-- Mã lớp: 22CLC03
-- MSSV: 22127034
-- Họ tên: Trần Gia Bảo
-- Mã đề:
-- Vị trí: Dòng 6 - Cột 8

-- TEST
SELECT * FROM GIAODICH
SELECT * FROM TAIKHOAN
SELECT * FROM LOAITAIKHOAN
SELECT * FROM KHACHHANG